# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Acerca de
    url: '#about'
    weight: 10
  - name: Publicaciones
    url: '#publications'
    weight: 30
  - name: Posteos
    url: '#posts'
    weight: 50
  - name: Cursos realizados
    url: '#accomplishments'
    weight: 60
  - name: Premios y Subsidios
    url: '#awards-funding'
    weight: 70
  - name: Contacto
    url: '#contact'
    weight: 100
